version: '3.9'


services:
  postgres:
    container_name: polylink-postgres
    image: db
    build:
      context: .
      target: db
    networks:
        - polylink-network
    environment:
        POSTGRES_USER: root
        POSTGRES_PASSWORD: password
        POSTGRES_DB: polylink
    ports:
      - 5000:5432

networks:
  polylink-network:
    name: polylink-network
    external: true

