version: '3'


services:
  postgres:
    container_name: polylink-postgres
    image: postgres
    environment:
        POSTGRES_USER: root
        POSTGRES_PASSWORD: password
        POSTGRES_DB: PolyLink
    ports:
      - 5431:5431

