CREATE TABLE "users_polylink" (
  "id" varchar PRIMARY KEY,
  "firstname" varchar,
  "lastname" varchar,
  "email" varchar UNIQUE,
  "city" varchar,
  "city_code" int,
  "work_field" varchar,
  "cv_link" varchar
);

CREATE TABLE "employement" (
  "offer" int,
  "employee" varchar,
  "employee_rate" int,
  "employer_rate" int,
  PRIMARY KEY ("offer", "employee")
);

CREATE TABLE "apply" (
  "offer" int,
  "employee" varchar,
  "date" date,
  PRIMARY KEY ("offer", "employee")
);

CREATE TABLE "offer" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar,
  "description" varchar,
  "start_date" date,
  "end_date" date,
  "city" varchar,
  "city_code" int,
  "nb_positions" int,
  "salary" int,
  "advantage" varchar,
  "employer" varchar
);

ALTER TABLE "offer" ADD FOREIGN KEY ("employer") REFERENCES "users_polylink" ("id");

ALTER TABLE "apply" ADD FOREIGN KEY ("offer") REFERENCES "offer" ("id");

ALTER TABLE "apply" ADD FOREIGN KEY ("employee") REFERENCES "users_polylink" ("id");

ALTER TABLE "employement" ADD FOREIGN KEY ("offer") REFERENCES "offer" ("id");

ALTER TABLE "employement" ADD FOREIGN KEY ("employee") REFERENCES "users_polylink" ("id");
