CREATE TABLE "employer" (
  "id" varchar PRIMARY KEY,
  "firstname" varchar,
  "lastname" varchar,
  "email" varchar UNIQUE,
  "head_office_city" varchar,
  "head_office_city_code" int,
  "work_field" varchar
);

CREATE TABLE "jobseeker" (
  "id" varchar PRIMARY KEY,
  "firstname" varchar,
  "lastname" varchar,
  "email" varchar UNIQUE,
  "city" varchar,
  "city_code" int,
  "work_field" varchar,
  "cv_link" varchar
);

CREATE TABLE "recruiting" (
  "offer" int,
  "employee" varchar,
  "employee_rate" int,
  "employer_rate" int,
  PRIMARY KEY ("offer", "employee")
);

CREATE TABLE "apply" (
  "offer" int,
  "applicant" varchar,
  "date" date,
  PRIMARY KEY ("offer", "applicant")
);

CREATE TABLE "offer" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar,
  "description" varchar,
  "start_date" date,
  "end_date" date,
  "city" varchar,
  "city_code" int,
  "nb_positions" int,
  "salary" int,
  "advantage" varchar,
  "employer" varchar
);

ALTER TABLE "apply" ADD FOREIGN KEY ("applicant") REFERENCES "jobseeker" ("id");

ALTER TABLE "apply" ADD FOREIGN KEY ("offer") REFERENCES "offer" ("id");

ALTER TABLE "offer" ADD FOREIGN KEY ("employer") REFERENCES "employer" ("id");

ALTER TABLE "recruiting" ADD FOREIGN KEY ("offer") REFERENCES "offer" ("id");

ALTER TABLE "recruiting" ADD FOREIGN KEY ("employee") REFERENCES "jobseeker" ("id");
