CREATE TABLE "user" (
                        "id_user" int PRIMARY KEY,
                        "firstname" varchar,
                        "lastname" varchar,
                        "email" varchar UNIQUE,
                        "city" varchar,
                        "city_code" int,
                        "work_field" varchar,
                        "cv_link" varchar
);

CREATE TABLE "user_roles" (
                              "user_id" int,
                              "role_id" int,
                              PRIMARY KEY ("user_id", "role_id")
);

CREATE TABLE "role" (
                        "id_role" int PRIMARY KEY,
                        "name" varchar
);

CREATE TABLE "recruiting" (
                              "id_offer" int,
                              "id_employee" int,
                              "employee_rate" int,
                              "employer_rate" int,
                              "last_updated" timestamp,
                              PRIMARY KEY ("id_offer", "id_employee")
);

CREATE TABLE "apply" (
                         "id_offer" int,
                         "id_applicant" int,
                         "last_updated" timestamp,
                         PRIMARY KEY ("id_offer", "id_applicant")
);

CREATE TABLE "offer" (
                         "id_offer" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         "id_employer" int,
                         "title" varchar,
                         "description" varchar,
                         "keywords" varchar,
                         "start_date" date,
                         "end_date" date,
                         "city" varchar,
                         "city_code" int,
                         "nb_positions" int,
                         "salary" int,
                         "advantage" varchar
);

CREATE TABLE "recommandation" (
                                  "id_offer" int,
                                  "id_jobseeker" int,
                                  "last_updated" timestamp
);

ALTER TABLE "apply" ADD FOREIGN KEY ("id_offer") REFERENCES "offer" ("id_offer");

ALTER TABLE "recruiting" ADD FOREIGN KEY ("id_offer") REFERENCES "offer" ("id_offer");

ALTER TABLE "apply" ADD FOREIGN KEY ("id_applicant") REFERENCES "user" ("id_user");

ALTER TABLE "recruiting" ADD FOREIGN KEY ("id_employee") REFERENCES "user" ("id_user");

ALTER TABLE "offer" ADD FOREIGN KEY ("id_employer") REFERENCES "user" ("id_user");

ALTER TABLE "user_roles" ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id_user");

ALTER TABLE "user_roles" ADD FOREIGN KEY ("role_id") REFERENCES "role" ("id_role");